CREATE TABLE GRID_NAME
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE CHECK ( TRIM(NAME) <> '' )
);

CREATE INDEX IDX_NAME_UPPER ON GRID_NAME (UPPER(NAME));

CREATE TABLE GRID_COLUMN
(
    ID                      BIGSERIAL PRIMARY KEY,
    GRID_NAME_ID            BIGINT       NOT NULL REFERENCES GRID_NAME (ID) ON DELETE CASCADE,
    FIELD                   VARCHAR(50)  NOT NULL CHECK ( TRIM(FIELD) <> '' ),
    HEADER                  VARCHAR(100) NOT NULL CHECK ( TRIM(HEADER) <> '' ),
    DATA_TYPE               VARCHAR(50)  NOT NULL CHECK ( TRIM(DATA_TYPE) <> '' ),
    SORTABLE                BOOLEAN      NOT NULL DEFAULT TRUE,
    DEFAULT_SORT_ORDER      VARCHAR(5) CHECK ( DEFAULT_SORT_ORDER IS NULL OR DEFAULT_SORT_ORDER IN ('asc', 'desc')),
    FILTERABLE              BOOLEAN      NOT NULL DEFAULT TRUE,
    DEFAULT_FILTER_OPERATOR VARCHAR(30) CHECK ( DEFAULT_FILTER_OPERATOR IS NULL OR TRIM(DEFAULT_FILTER_OPERATOR) <> '' ),
    WIDTH                   INTEGER CHECK ( WIDTH >= 0 ),
    ALIGN                   VARCHAR(10)  NOT NULL DEFAULT 'LEFT' CHECK ( ALIGN IN ('LEFT', 'RIGHT', 'CENTER')),
    VISIBLE                 BOOLEAN               DEFAULT TRUE,
    VISIBLE_INDEX           INTEGER CHECK ( VISIBLE_INDEX >= 0 ),
    CELL_TEMPLATE           VARCHAR(100) CHECK ( CELL_TEMPLATE IS NULL OR TRIM(CELL_TEMPLATE) <> '' )
);

CREATE TABLE GRID_PERSONALIZATION
(
    ID           BIGSERIAL PRIMARY KEY,
    GRID_NAME_ID BIGINT NOT NULL REFERENCES GRID_NAME (ID) ON DELETE CASCADE,
    USER_ID      BIGINT NOT NULL,
    GRID_COLUMN  JSONB  NOT NULL
);

ALTER TABLE GRID_PERSONALIZATION
    ADD CONSTRAINT UQ_GRID_USER UNIQUE (GRID_NAME_ID, USER_ID);

CREATE INDEX IDX_GRID_NAME_ID_USER_ID ON GRID_PERSONALIZATION (GRID_NAME_ID, USER_ID);