server:
  port: 1003
spring:
  application:
    name: warehouse
  datasource:
    url: jdbc:postgresql://localhost:5432/personal_finance_dev
    username: personal_finance_dev
    password: personal_finance_dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

bulk-upload:
  base-folder:
    in-progress: E:/BulkUploads/in-progress
    success: E:/BulkUploads/success
    error: E:/BulkUploads/error


#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.orm.jdbc.extract: TRACE